version: '3.7'


# container to run tests and other developer activities
services:
  php:
    container_name: floating-iterable
    image: floating-iterable
    build:
      context: php
    volumes:
      - ./../:/var/app:cached
